scoreboard:
  default-enabled: true
  update-ticks: 20

  title:
    frame-ticks: 10
    frames:
      - '<gradient:#DCF6E4:#2BD89F><bold>OEssentials</bold></gradient>'
      - '<gradient:#2BD89F:#017E6B><bold>OEssentials</bold></gradient>'
      - '<gradient:#017E6B:#0A4C47><bold>OEssentials</bold></gradient>'
      - '<gradient:#B1DECB:#2BD89F><bold>OEssentials</bold></gradient>'

  worlds:
    whitelist: []
    blacklist: []

  lines:
    - |-
      %animations_<tag interval=5>
      <gradient:#DCF6E4:#2BD89F>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#2BD89F:#017E6B>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#017E6B:#0A4C47>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#0A4C47:#2BD89F>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#2BD89F:#DCF6E4>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      </tag>%

    - ''

    - '<#B1DECB>Player:</#B1DECB> <#DCF6E4>{player}</#DCF6E4>'

    - '<#B1DECB>Rank:</#B1DECB> <#2BD89F>%luckperms_prefix%%luckperms_primary_group_name%</#2BD89F>'

    - ''

    - |-
      %animations_<tag interval=10>
      <gradient:#DCF6E4:#2BD89F>Balance:</gradient> <#DCF6E4>%vault_eco_balance_formatted%</#DCF6E4>
      |
      <gradient:#2BD89F:#017E6B>Balance:</gradient> <#B1DECB>%vault_eco_balance_formatted%</#B1DECB>
      |
      <gradient:#017E6B:#2BD89F>Balance:</gradient> <#DCF6E4>%vault_eco_balance_formatted%</#DCF6E4>
      |
      <gradient:#2BD89F:#DCF6E4>Balance:</gradient> <#B1DECB>%vault_eco_balance_formatted%</#B1DECB>
      </tag>%

    - ''

    - '<#B1DECB>Online:</#B1DECB> <#2BD89F>%oreo_network_online%</#2BD89F><#0A4C47>/</#0A4C47><#DCF6E4>%server_max_players%</#DCF6E4>'

    - ''

    - |-
      %animations_<tag interval=5>
      <gradient:#DCF6E4:#2BD89F>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#2BD89F:#017E6B>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#017E6B:#0A4C47>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#0A4C47:#2BD89F>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      |
      <gradient:#2BD89F:#DCF6E4>━━━━━━━━━━━━━━━━━━━━━━</gradient>
      </tag>%

    - '<gradient:#2BD89F:#DCF6E4><italic>play.example.com</italic></gradient>'